### ISSUE TITLE
 How to specify the flash path？--ppapi-flash-path=".\plugins\pepflashplayer.dll"

### ISSUE THREAD

**Issue by mxzxck** [portapps/ungoogled-chromium-portable#12]
#### Steps to reproduce this issue

1.
2.
3.

#### Expected behaviour

> Tell me what should happen

#### Actual behaviour

> Tell me what happens instead

### Configuration

**App release / arch (ex. 1.0.0-2 win64)** :

**Operating system (ex. Windows 10 Pro 64 bits)** :

**Winver screenshot** :

> Open a command prompt and type winver then take / save the screenshot of the window and drag the image file in this issue. For example: http://bit.ly/2vA5sxR

### Screenshots

> If applicable, add screenshots to help explain your problem.

### Logs

Join the log file `log\[appname]-portable.log` to this issue.

**Comment by crazy-max** [comment]
Ask [here](https://github.com/macchrome/winchrome/) or [here](https://github.com/ungoogled-software/ungoogled-chromium-windows).
