### ISSUE TITLE
Sample config yaml file always created

### ISSUE THREAD

**Issue by oriceon** [portapps/ungoogled-chromium-portable#16]
Hello, why ungoogled-chromium-portable.sample.yml is created every time i opened ungoogled-chromium-portable.exe and not just at first run?

Or to check if ungoogled-chromium-portable.yml exist and if not then to create the sample one...

**Comment by crazy-max** [comment]
@oriceon portapps/portapps#62

**Comment by oriceon** [comment]
@crazy-max and no fix untill now? From 2019? :)
