### ISSUE TITLE
Spelling not working?

### ISSUE THREAD

**Issue by angelog0** [portapps/ungoogled-chromium-portable#2]
I don't knows if this is an issue or a feature of ungoogled-chromium but it seems that the spelling, being enabled in the settings (both for Italian and English), is not working. The wrong typed word aren't red underlined, they appear as if they were correct typed.

I tested this in a clean installation of your package: just unpack the `.7z' archive in e folder, start the ungoogled-C portable, choose DuckDuckGo search engine and type some wrong word, change the language (Italian <--> English): the typed words appear always as if they were right.

Chromium (not ungoogled and not portable) from [here](https://chromium.woolyss.com) works as expected.

Attached two screenshots, one with ungoogled-chromium portable from PortApps and one from Chromiun (NOT ungoogle, not portable) from Woolyss.
[screenshot.tar.gz](https://github.com/portapps/ungoogled-chromium-portable/files/4417821/screenshot.tar.gz)

**Comment by crazy-max** [comment]
Portapps don't bring support directly to provided apps. If you've got an issue with ungoogled-chromium, open an issue on the [official repository](https://github.com/Eloston/ungoogled-chromium). Thanks.

PS: Does it works with this release: https://github.com/macchrome/winchrome/releases/download/v80.0.3987.149-r989-Win64/ungoogled-chromium-80.0.3987.149-1_windows.7z ?

**Comment by angelog0** [comment]
> 
> PS: Does it works with this release: https://github.com/macchrome/winchrome/releases/download/v80.0.3987.149-r989-Win64/ungoogled-chromium-80.0.3987.149-1_windows.7z ?

No. Thanks and sorry for the noise it seems an old [story](https://github.com/Eloston/ungoogled-chromium/issues/188)

Be free to close this.

**Comment by angelog0** [comment]
Any chance of getting Chromium portable? Thanks
