### ISSUE TITLE
Won't open

### ISSUE THREAD

**Issue by dvoraking** [portapps/ungoogled-chromium-portable#22]
It was working fine yesterday. Now I get this error:

cannot unmarshal portapp-prev: invalid character '\x00' looking for beginning of value

I installed a fresh version and it worked. However, I have a lot of stuff saved on the old one. I tried reinstalling over the old one, or deleting it, making a fresh install and restoring the deleted files, but the problem persists.

**Comment by crazy-max** [comment]
@dvoraking Can you create a proper [bug report](https://github.com/portapps/ungoogled-chromium-portable/issues/new?template=bug_report.md) please? And also can you paste the content of `portapp-prev.json`? Thanks.

**Comment by dvoraking** [comment]
I made a new install and transferred everything over from log and data, so that seems to have solved it.
