### ISSUE TITLE
update

### ISSUE THREAD

**Issue by Evolve6996** [portapps/ungoogled-chromium-portable#31]
thanks for your job it's amazing ❤️ 
 please update chromium portable more frequently currently latest version is 94 while the latest portable is 92

**Comment by crazy-max** [comment]
> please update chromium portable more frequently currently latest version is 94 while the latest portable is 92

As explained [on this page](https://portapps.io/doc/reporting-issue/): "We are aware of and notified of new application updates. So there’s no need to create an issue to update an application.".

Also feel free to contribute.
