### ISSUE TITLE
Update ungoogled-chromium-portable to 98.0.4758.80

### ISSUE THREAD

**Issue by 3oheicrw** [portapps/ungoogled-chromium-portable#35]
ungoogled-chromium 98.0.4758.80 released.

https://github.com/Eloston/ungoogled-chromium/releases/tag/98.0.4758.80-1

**Comment by crazy-max** [comment]
@3oheicrw As explained [on this page](https://portapps.io/doc/reporting-issue/), "We are aware of and notified of new application updates. So there’s no need to create an issue to update an application.". But feel free to open a PR.
