### ISSUE TITLE
Could you upgrade it to the latest version?

### ISSUE THREAD

**Issue by John-foobar-Doe** [portapps/ungoogled-chromium-portable#53]
I noticed that the Brave portable has been updated more frequently, whereas ungoogled-chromium portable's version is lagging quite a lot behind the official one. So could you please update it to the latest official version?

Alternatively, will it be working properly if I simply download the latest windows_x64.zip from https://github.com/ungoogled-software/ungoogled-chromium-windows/releases and extract it to & overwrite `X:\ungoogled-chromium-portable\app\`? Or will this mess up the existing folder `X:\ungoogled-chromium-portable\` or cause any problem?

Many thanks.

**Comment by ioc2e3** [comment]
> I noticed that the Brave portable has been updated more frequently, whereas ungoogled-chromium portable's version is lagging quite a lot behind the official one. So could you please update it to the latest official version?

Same opinion ...

Hope , increase update frequency ...

.
