### ISSUE TITLE
Request: Please can you credit Marmaduke, the main developer of your Chromium release? 

### ISSUE THREAD

**Issue by woolyss** [portapps/ungoogled-chromium-portable#9]
Hello @crazy-max: I salute your effort to make a portable version of Chromium. 👍
https://github.com/portapps/ungoogled-chromium-portable

Please, can you credit the source of your Chromium releases which is done by Marmaduke (@macchrome)?

Indeed, Marmaduke is the only developer on the Web who compile the **latest stable Chromium** versions with support of **all codecs** (H.264, H.265...) and the **Widevine** plugin. Note: the support of H.265/HEVC ([Online audio/video tester](https://tools.woolyss.com/html5-audio-video-tester/)) in Chromium is not documented at all. [Most of browser does not support it](https://caniuse.com/#feat=hevc). So it is difficult to reproduce this release.
* His profile: https://github.com/macchrome
* His "ungoogled" releases: https://github.com/macchrome/winchrome/releases

The **Windows versions** from the Eloston repository **are all outdated**.
* https://github.com/Eloston/ungoogled-chromium/#downloads
* https://ungoogled-software.github.io/ungoogled-chromium-binaries/

After that, I can promote your work on our site if you want.
It means a link of your portable release at https://chromium.woolyss.com/ for the corresponding Marmaduke's "ungoogled" release. 😉

Thank you very much.

Contact me in private (https://info.woolyss.com/) if you prefer.

Regards.

**Comment by crazy-max** [comment]
Hi @woolyss,

> Please, can you credit the source of your Chromium releases which is done by Marmaduke (@macchrome)?

Sure I will add a note in the README, thanks for your input!

**Comment by crazy-max** [comment]
@woolyss [Done](https://github.com/portapps/ungoogled-chromium-portable#credits).

**Comment by woolyss** [comment]
@crazy-max: Thank you very much. I added a link to your Chromium releases on our website. 😉
https://chromium.woolyss.com/

**Comment by dm17** [comment]
@woolyss Can you help dispel some misconceptions and make it easy for us to stay informed on the privacy/security aspects of ungoogled-chromium: what are the exact privacy/security differences between Eloston's and Marmaduke's ungoogled-chromium builds?
Thanks!

**Comment by woolyss** [comment]
@dm17 Please, check you mailbox ;)

**Comment by dm17** [comment]
> @dm17 Please, check your mailbox ;)

Thanks, but I have to say the email did not include anything directly about privacy patch differences between Marmaduke's and Eloston's ungoogled-chromium. Perhaps it is a suggestion to look at the latest patches and just compare them?

**Comment by woolyss** [comment]
As I said before, Maramaduke uses all patches apart from "Safe Browser".
You can check that for each release: 
https://github.com/macchrome/winchrome/releases/tag/v87.0.4280.88-r812852-Win64

This release was compiled Friday, December 4, 2020. So, Maramaduke used all latest ungoogled-chromium patches from the Eloston's project (except the safebrowsing patch, like mentioned))
https://github.com/Eloston/ungoogled-chromium/tree/master/patches 
https://github.com/Eloston/ungoogled-chromium/commits/master/patches (history of changes)
As you can see the last patch was fixed on December 4, 2020

Like for each binary, you must trust its developer. If you don't trust him/her, do it yourself! ^^

-------

![1](https://user-images.githubusercontent.com/17823851/103216492-1e339980-490e-11eb-8be0-1059a1edaeae.jpg)

**Comment by dm17** [comment]
Hey Jerry,
I found this awesome thread to do with deduplicating, streamlining, and
optimizing degoogled chromium development efforts:
https://github.com/Eloston/ungoogled-chromium/discussions/1395#discussioncomment-726202
Hopefully you can participate as well :)
